# Generated by Django 3.0.7 on 2020-06-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200612_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rank',
            field=models.IntegerField(),
        ),
    ]
